#!/bin/bash

if $(! git status -s $PWD &> /dev/null)
    then
        echo "no git repo"
    else
    if [[ $(git status --porcelain $PWD) == "" ]]
    then
        echo "no"
    else
        echo "yes"
    fi
fi
